# Practical-04

## Q-1

In [6]:
import pandas as pd
data = {'X' : [4,6,8,5,7] ,
         'Y' : [7,9,10,8,11] }
df = pd.DataFrame(data)

df.to_csv("bivariate_data.csv",index=False) #index=False avoids extra numbering column
df.head() # .head() shows first 5 rows

X   Y
0  4   7
1  6   9
2  8  10
3  5   8
4  7  11

## Q-2

In [14]:
df = pd.read_csv('bivariate_data.csv')
df

array([[ 4,  7],
       [ 6,  9],
       [ 8, 10],
       [ 5,  8],
       [ 7, 11]])

In [19]:
import numpy as np
data_array = df.to_numpy()
data_array

array([[ 4,  7],
       [ 6,  9],
       [ 8, 10],
       [ 5,  8],
       [ 7, 11]])

## Q-3

In [16]:
x = data_array[:,0]
y = data_array[:,1]
print('x is ',x,'and y is',y)

x is  [4 6 8 5 7] and y is [ 7  9 10  8 11]


## Q-4

In [28]:
data_matrix = np.array([ [ 4,  7],
       [ 6,  9],
       [ 8, 10],
       [ 5,  8],
       [ 7, 11]])
data_matrix

array([[ 4,  7],
       [ 6,  9],
       [ 8, 10],
       [ 5,  8],
       [ 7, 11]])

In [27]:
transpose_matrix = data_matrix.T
transpose_matrix

array([[ 4,  6,  8,  5,  7],
       [ 7,  9, 10,  8, 11]])

In [29]:
# addition = data_matrix + transpose_matrix
# Matrix addition of a matrix and its transpose is defined only if the matrix is square.

In [30]:
product_matrix = np.dot(data_matrix,transpose_matrix)
product_matrix

array([[ 65,  87, 102,  76, 105],
       [ 87, 117, 138, 102, 141],
       [102, 138, 164, 120, 166],
       [ 76, 102, 120,  89, 123],
       [105, 141, 166, 123, 170]])

In [ ]:
#'''A matrix is invertible if: It is square & Determinant ≠ 0'''

In [33]:
# Only square matrices can have inverses
inv_matrix = np.linalg.inv(product_matrix)
inv_matrix

array([[-4.48111973e+14, -5.47144739e+14, -2.81336069e+12,
         4.75268150e+14,  5.30556852e+13],
       [-7.44552989e+16, -4.69721766e+16, -9.65383166e+15,
         5.49404387e+16,  5.55033886e+16],
       [ 2.56937449e+29,  4.40464199e+29, -1.83526750e+28,
        -2.93642799e+29, -2.93642799e+29],
       [ 4.62487409e+30,  7.92835558e+30, -3.30348149e+29,
        -5.28557039e+30, -5.28557039e+30],
       [-3.59712429e+30, -6.16649879e+30,  2.56937449e+29,
         4.11099919e+30,  4.11099919e+30]])

In [36]:
row_sum = data_matrix.sum(axis=1)
column_sum = data_matrix.sum(axis=0)
print('Row sums of data_matrix',row_sum)
print('Column sums of data_matrix',column_sum)

Row sums of data_matrix [11 15 18 13 18]
Column sums of data_matrix [30 45]


In [38]:
eigen_values , eigen_vectors = np.linalg.eig(product_matrix)
eigen_values
eigen_vectors

array([[-0.32731821, -0.82274409, -0.46470954, -0.00096919, -0.07139171],
       [-0.4403613 ,  0.20237336, -0.04812299, -0.00231309, -0.53723911],
       [-0.51966037, -0.24573908,  0.80109111,  0.04399124,  0.11452654],
       [-0.38383976,  0.29753703, -0.25641627,  0.78974895,  0.80671887],
       [-0.53062686,  0.36499481, -0.27245726, -0.61184563, -0.20582931]])

## Q-5

In [41]:
x_mean = np.mean(x)
y_mean = np.mean(y)
print('Sample mean of x :',x_mean)
print('Sample mean of y :',y_mean)

Sample mean of x : 6.0
Sample mean of y : 9.0


In [42]:
var_covar_matrix = np.cov(x,y)
print('Variance-Covariance matrix of x,y is :',var_covar_matrix)

Variance-Covariance matrix of x,y is : [[2.5  2.25]
 [2.25 2.5 ]]
